export enum UserRole {
  INDIVIDUAL = 'INDIVIDUAL',
  CBT_CENTER = 'CBT_CENTER',
  CBT_STAFF = 'CBT_STAFF',
  TENANT_ADMIN = 'TENANT_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DISPUTED = 'DISPUTED',
  RESOLVED = 'RESOLVED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum TransactionType {
  WALLET_FUNDING = 'WALLET_FUNDING',
  SERVICE_PURCHASE = 'SERVICE_PURCHASE',
  ESCROW_LOCK = 'ESCROW_LOCK',
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  PLATFORM_COMMISSION = 'PLATFORM_COMMISSION',
  CBT_COMMISSION = 'CBT_COMMISSION',
  WITHDRAWAL = 'WITHDRAWAL',
  REFUND = 'REFUND',
  PENALTY = 'PENALTY',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum FulfillmentType {
  MANUAL = 'MANUAL',
  AUTOMATED = 'AUTOMATED',
}

export enum ServiceDeliveryMode {
  CBT_MANUAL = 'CBT_MANUAL',
  API_AUTOMATED = 'API_AUTOMATED',
  PIN_STOCK = 'PIN_STOCK',
}

export enum ServiceCategory {
  JAMB = 'JAMB',
  NIMC = 'NIMC',
  NECO = 'NECO',
  VTU_AIRTIME = 'VTU_AIRTIME',
  VTU_DATA = 'VTU_DATA',
  VTU_CABLE_TV = 'VTU_CABLE_TV',
  VTU_ELECTRICITY = 'VTU_ELECTRICITY',
}

export enum CbtApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED_FOR_REQUESTER = 'RESOLVED_FOR_REQUESTER',
  RESOLVED_FOR_CBT = 'RESOLVED_FOR_CBT',
  REDO_REQUESTED = 'REDO_REQUESTED',
}

export enum WithdrawalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

export enum NotificationType {
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_ASSIGNED = 'ORDER_ASSIGNED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  DISPUTE_RAISED = 'DISPUTE_RAISED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  WITHDRAWAL_APPROVED = 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED = 'WITHDRAWAL_REJECTED',
  WALLET_FUNDED = 'WALLET_FUNDED',
  CBT_APPROVED = 'CBT_APPROVED',
  CBT_REJECTED = 'CBT_REJECTED',
  JOB_AVAILABLE = 'JOB_AVAILABLE',
}

export enum PaymentGateway {
  FINTAVAPAY = 'FINTAVAPAY',
  FLUTTERWAVE = 'FLUTTERWAVE',
}

export enum OtpType {
  EMAIL_VERIFY = 'EMAIL_VERIFY',
  PHONE_VERIFY = 'PHONE_VERIFY',
  PASSWORD_RESET = 'PASSWORD_RESET',
  LOGIN_2FA = 'LOGIN_2FA',
}
